### PR TITLE
<deleted>

### PR DESCRIPTION
**Pull request by yyaremenko**

### CODE REVIEW

**Comment by yyaremenko** [comment]
also, the tests are failing... after docu

**Comment by nicolas-grekas** [comment]
When the numbers come from standards like HTTP, we prefer the actual value.

**Comment by yyaremenko** [comment]
why do you have a whole set of constants for HTTP codes in a Response class then?

**Comment by yyaremenko** [comment]
...and zero response in a week, so classy of symfony devs )) anw.

**Pull request closed without merging**
