### PR TITLE
[TwigComponent][Example] Paginated list

### PR DESCRIPTION
**Pull request by gilles-g**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no 
| Tickets       |
| License       | MIT

Add example of a twig component for paginated list

image

It's not a LiveComponent, but an example of TwigComponent

### CODE REVIEW

**Comment by norkunas** [comment]
Did you forgot to add `src/Twig/PaginatedList.php` file?
Also I think there is no point in validating component values in `preMount` and instead make them non-nullable so the php itself would validate them

**Comment by gilles-g** [comment]
@norkunas Yes I forgot some files ignored by git :thinking: 
I removed preMount, but I see I have forgot to add a screenshot in the demo list, but I prefer to wait

**Comment by weaverryan** [comment]
Yo @gilles-g! Did you mean to close this? Tbh, it fell through the cracks and I missed it when you opened it.

**Comment by gilles-g** [comment]
Hi,
Don't worry,I think I will propose a new PR later!

**Comment by weaverryan** [comment]
Ok, I hope so - sorry about that!

**Pull request closed without merging**
