### PR TITLE
[Autocomplete] Allow configuring TomSelect’s `labelField`

### LINKED ISSUE #2375: [Autocomplete] Support `labelField` options
I’m currently using a DTO to store entities data besides their `text` and `value` in TomSelect options. I wanted its properties to match our model; e.g. by setting [`valueField`](https://tom-select.js.org/docs/#valuefield) to `id` I can make TomSelect use the DTO’s `$id` property to populate options’ value. This works great, but not for [`labelField`](https://tom-select.js.org/docs/#labelfield) because its default value (`text`) is hardcoded in `score`, `render.item` and `render.option`.

Would it be possible to make this property depends on the `labelField` option? Thanks!

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Issues        | Fix #2375
| License       | MIT

### CODE REVIEW

**Review by Kocal — APPROVED** [review]
LGTM

**Comment by smnandre** [comment]
@MatTheCat thank you :) 

A small changelog update + maybe doc mention ? 

And LGTM indeed!

**Comment by MatTheCat** [comment]
Added a changelog entry :ok_hand: 

This would be part of `tom_select_options` but the documentation does not provide the list of supported ones so I’m not sure how I could document this.

**Review by smnandre — APPROVED** [review]
Thx @MatTheCat !

**Comment by Kocal** [comment]
Thank you @MatTheCat.

**Pull request merged**
