### PR TITLE
[Map][Google] Add documentation about `ux_map.google_maps.default_map_id` 

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no 
| Issues        | Fix #... 
| License       | MIT

I've just tilted that I've missed to document the new feature introduced in #2350 for #2306

### CODE REVIEW

**Review by kbond — APPROVED** [review]

**Comment by smnandre** [comment]
Did you update the google mpas recipe ?

**Review by smnandre — APPROVED** [review]

**Comment by Kocal** [comment]
> Did you update the google mpas recipe ?


Not yet

**Comment by Kocal** [comment]
Opened https://github.com/symfony/recipes/pull/1354

**Comment by Kocal** [comment]
When you will install UX Google Map 2.22 for the first time (or update the recipe) ✨ 
image

**Comment by smnandre** [comment]
This is really nice! 👏

**Pull request merged**
