### PR TITLE
[Site] Support page

### PR DESCRIPTION
**Pull request by smnandre**
Minimal / simple page to list support options

Capture d’écran 2024-08-22 à 06 23 30

You had @WebMamba something like this in mind ?

### CODE REVIEW

**Comment by kbond** [comment]
I like this!

**Comment by Kocal** [comment]
What about the logo to the left of the title?

**Comment by smnandre** [comment]
> What about the logo to the left of the title?

Two reasons i kept it top of the title
* i wanted to change a bit from the "PackageBox", have some variety in card layouts
* i have something in mind for the top right space but i'd like to see if the page is used, first :) 

But no problem if you prefer, i don't really mind here :))

**Comment by kbond** [comment]
Make sense. Let's roll with this!

**Comment by Kocal** [comment]
> > What about the logo to the left of the title?
> 
> Two reasons i kept it top of the title
> 
> * i wanted to change a bit from the "PackageBox", have some variety in card layouts
> * i have something in mind for the top right space but i'd like to see if the page is used, first :)
> 
> But no problem if you prefer, i don't really mind here :))

Okay, let's keep it that way then :)

**Review by Kocal — APPROVED** [review]

**Comment by smnandre** [comment]
Capture d’écran 2024-08-22 à 23 17 03

**Review by Kocal — APPROVED** [review]
Works fine in light/dark modes, and in mobile too:
Capture d’écran 2024-08-23 à 00 34 12
image
image

**Comment by Kocal** [comment]
Thank you @smnandre.

**Pull request merged**
