### PR TITLE
Adding support for Chartjs 3

### LINKED ISSUE #86: [Chart.js] v3 support
Currently Symfony UX offers version 2.9.4 of Chart.js.
In december and the beginning of 2021 it was good.

But since april version 3 has been released. And we are already at 3.2 as I write this.

I also think it would be a good idea to specify on the repository readme (for each integration) which version is supported (or did I not see it?).
It would have saved me a few hours of trying to figure out why certain options weren't working.

[Migration guide](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html)

Can you tell us what the procedure would be for the update?

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tickets       | Fixes #86
| License       | MIT

This takes the work from #126 and rebases so we can finish on the 2.x branch.

### CODE REVIEW

**Comment by tgalopin** [comment]
There seems to be a missing browser feature required by Chartjs 3 (ResizeObserver), perhaps would it be necessary to add a new polyfill.

**Comment by weaverryan** [comment]
> There seems to be a missing browser feature required by Chartjs 3 (ResizeObserver), perhaps would it be necessary to add a new polyfill.

You're right - it WAS missing in the test environment. I polyfilled it there. But I don't think we need to polyfill it for the users, if that's what you meant (let me know if that IS what you were thinking and let's chat).

I have just one more tweak on this one - it's in the "externals" of the built file (if you build the file right now, the dist file will "contain" chartjs instead of just having the `import line`). I know the fix - I just need to make a nice addition to the build system for it.

**Comment by weaverryan** [comment]
This is now ready!

**Comment by tgalopin** [comment]
Could you squash your commits? I can't do it automatically due to two authors :)

**Review by tgalopin — APPROVED** [review]

**Comment by Huluti** [comment]
ChartJS is now at v3.6.2. Is it something to change in this PR since it's based on v3.4.1?

**Comment by weaverryan** [comment]
The 3.4.1 only means that it's the minimum version. In reality, if you installed this, you would have `^3.4.1` in your package.json, but yarn/npm would install the latest version 3 (so 3.6.2). It's really not a big deal one way or another, but I'd say just keep it.

I've got it rebased to only 2 commits - that's how (I think) we should keep it.

**Comment by tgalopin** [comment]
Thanks @weaverryan.

**Pull request merged**
