### PR TITLE
[Chart] Add a small example how to set options

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Tickets       | 
| License       | MIT

Adding a small example how to set chart options. 

The docs for this example is [here](https://www.chartjs.org/docs/latest/axes/cartesian/#tick-configuration) and personally I find it next to impossible to discover what options are available... This example may help people just a bit.

### CODE REVIEW

**Comment by tgalopin** [comment]
Shouldn't we put this in the README instead?

**Comment by Nyholm** [comment]
I added it in the readme too

**Review by nicolas-grekas — APPROVED** [review]
(I pushed some CS fixes)

**Comment by tgalopin** [comment]
Thanks Tobias.

**Pull request merged**
