### PR TITLE
chore: check if fabbot is correctly working

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Issues        | Fix #... 
| License       | MIT

PR opened for Fabien.

 Following #1996, we need to understand if something is wrong with fabbot or not.
⚠️ **This PR should not be merged!**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
`fabbot` seems to be working ... so maybe it was a temporary error?

**Comment by Kocal** [comment]
fabbot is green when it's supposed to be red, the code here is not valid (run PHP-CS-Fixer locally and see the diff). 

But I'm already seeing this problem with Fabien!
This afternoon he fixed the issue `Unable to parse the PHP CS Fixer configuration: %sSandboxed code attempted to call non-whitelisted class: PhpCsFixer\\Runner\\Parallel\\ParallelConfigFactory`, but there is still more one issue.

**Comment by smnandre** [comment]
(side topic: if we also could make a global pass with fabbot, to fix all the exceptions format at once, that'd be great)

**Comment by Kocal** [comment]
Okay, here fabbot is working as expected: 
image


Closing for now, let's observe other PR :eyes:

**Pull request closed without merging**
