### PR TITLE
Fix Doctrine Persistence deprecation

### PR DESCRIPTION
**Pull request by jmsche**
| Q             | A
| ------------- | ---
| Bug fix?      | yes (kinda)
| New feature?  | no
| Tickets       | N/A
| License       | MIT

This tiny PR fixes a deprecation coming from doctrine/persistence.

### CODE REVIEW

**Comment by jmsche** [comment]
Hmm the CI failures _seem_ unrelated.

**Comment by sneakyvv** [comment]
@jmsche You should trigger a rerun of the Turbo tests, since that test sometimes fails. Your change fixed the deprecation issues. 👍 
PS: triggering a rerun can be done by amending your commit and force-pushing the new commit.

**Comment by jmsche** [comment]
Thanks @sneakyvv :) 

It's only getting worse :D

**Comment by weaverryan** [comment]
Thanks! I'm going to merge 919 also and see where that leaves us

**Pull request merged**
