### PR TITLE
[TwigComponent] Fix TwigPreLexer edge case

### LINKED ISSUE #1306: lint:twig error, possibly with twig component
I've opened an issue at https://github.com/symfony/symfony/issues/52778, but posting here because I think it may have to do with symfony/ux-twig-component.

I wonder if I should actually post this to twigphp/twig?

I'm pretty sure it's a bug that was recently introduced, as I think the template referenced used to work.  @kbond , can you take a quick peek and at least tell me where to post this issue?

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix #1306
| License       | MIT

Quick fix to handle commented blocks in sublexer 

@weaverryan  @WebMamba  it may need a second look as i find weird the changes made do not have any other impacts...

### CODE REVIEW

**Comment by WebMamba** [comment]
Hum, I think if we have a problem with comments we also have an issue with the verbatim tag? And I think an easier solution could be if the pointer consumes `{#` then moves the pointer position to the next `#}` as we do at the top. With this method, you can remove all your condition

**Comment by smnandre** [comment]
I just wanted to fix the specific issue there.. and i guess a lot more people uses block in comments (in a dev phase it is a frequent thing) than verbatim :)  

But it's an issue indeed. 

I do believe we can fix _and improve_ some things here... but i'd suggest to do it a bit differently and that seems to me another (bigger) discussion. 

WDYT ? 
We can open an issue if you want to discuss this next move ?

**Comment by smnandre** [comment]
> Hum, I think if we have a problem with comments we also have an issue with the verbatim tag? And I think an easier solution could be if the pointer consumes `{#` then moves the pointer position to the next `#}` as we do at the top. With this method, you can remove all your condition

Sadly not if we want to handle properly verbatim + comments + strings +  ....

**Comment by weaverryan** [comment]
This moves things a small step forward - thanks Simon!

**Pull request merged**
