### PR TITLE
Replace JS toolchain by asset-mapper when testing ux-turbo

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Issues        | -
| License       | MIT

:speak_no_evil:

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Curiously, this fails on PHP 8.3 but passes on 8.4 (deps=high).
It's going to be fun to debug... If anyone is up to having a look, help welcome :)

**Comment by Kocal** [comment]
I will take a look tomorrow!

**Comment by Kocal** [comment]
Those issues were caused because the assets were not reachable with the webserver/browser ran by Panther:
image

It was fixed by compiling assets with `asset-map:compile`.

Now all that's left is this issue and we'll be good to go :)
image

**Comment by nicolas-grekas** [comment]
>It was fixed by compiling assets with asset-map:compile.

Super strange. I opened https://github.com/php/php-src/issues/16194 because this looks like a PHP bug to me.

**Comment by nicolas-grekas** [comment]
Thanks for the help @Kocal 

PR is ready.

**Review by Kocal — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Nice one! Thanks Nicolas

**Pull request merged**
