### PR TITLE
Allowing Symfony 6

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tickets       | None
| License       | MIT

We have an upcoming new major version (see #141), but I think we should support Symfony 6 in a minor release before that.

Cheers!

### CODE REVIEW

**Comment by weaverryan** [comment]
This is blocked by Panther's support for Symfony 6: https://github.com/symfony/panther/pull/509

**Comment by weaverryan** [comment]
Blocked either by a Panther 2.x release of this PR: https://github.com/symfony/panther/pull/513

**Comment by weaverryan** [comment]
This is ready. Once merged, I'd like to tag one more 1.x release for symfony/ux. Then we can prep for 2.0 with #141

**Review by kbond — APPROVED** [review]

**Comment by kbond** [comment]
Thank you @weaverryan.

**Pull request merged**
