### PR TITLE
Show a visible link to the docs of each package

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | #2273
| License       | MIT

I know that you mentioned that there's a work-in-progress effort to update some things in the current design (https://github.com/symfony/ux/issues/2273#issuecomment-2417350181) but I think we should fix this issue quickly because it's a problem in many long package pages.

If you don't like the proposed changes here it's fine; let's iterate over them. Tell me what to fix or change and I'll do it. Thanks!

This is how this PR looks at the moment:

#SymfonyHackday :)

### CODE REVIEW

**Comment by smnandre** [comment]
I'll open a PR this week-end (ideally sunday afternoon) -- probably loosely based on the stimulus bundle page "menu", with some simplification in markup + CSS, and some things to help us bring the next chapter :) 

But I see no problem to make this change in the meantime!

Do you think we could keep the current (flat) icon, with the color theme of the package ?

**Comment by smnandre** [comment]
@javiereguiluz I'm on it and pretty confident i'll open the PR soon... (@kbond can confirm if needed)

But depending on tonight, i may miss the deadline by a day or two... 
... as i have a clear roadmap on mind .. i needed to make some other changes :) 

Poke me if you want to have an "[avant-première](https://en.wikipedia.org/wiki/Film_screening)" ;)

**Comment by Kocal** [comment]
I'm working on it :eyes:

**Comment by Kocal** [comment]
Since nothing moved since October/November, I still believe this PR is useful until we rewrite packages pages. 

But, I've fixed the icon and its size, to be more consistent with the rest of the application:
image

**Review by kbond — APPROVED** [review]

**Comment by Kocal** [comment]
Thank you Javier.

**Comment by smnandre** [comment]
@Kocal  "Since nothing moved since October/November" ... this is not fair 😆  You were in the slack discussions about the redesign, and saw how the scope changed 😅

**Comment by Kocal** [comment]
Of course, but I mean on the live website / pull-requests :)

**Pull request merged**
