### PR TITLE
ux.symfony.com: upgrade symfony

### PR DESCRIPTION
**Pull request by bendavies**
| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | no
| Tickets       | 
| License       | MIT

Symfony 6.3 was released, so we can update from RC/dev versions

<details><summary>Changelogs</summary>
<p>

update symfony dependencies

Changelogs summary:

- symfony/runtime updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/runtime/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/runtime/releases/tag/v6.3.1

- symfony/routing updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/routing/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/routing/releases/tag/v6.3.1

- symfony/http-foundation updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/http-foundation/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/http-foundation/releases/tag/v6.3.1

- symfony/var-dumper updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/var-dumper/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/var-dumper/releases/tag/v6.3.1

- symfony/http-kernel updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/http-kernel/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/http-kernel/releases/tag/v6.3.1

- symfony/dependency-injection updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/dependency-injection/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/dependency-injection/releases/tag/v6.3.1

- symfony/filesystem updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/filesystem/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/filesystem/releases/tag/v6.3.1

- symfony/cache updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/cache/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/cache/releases/tag/v6.3.1

- symfony/framework-bundle downgraded from 6.3.x-dev@18165b0 to v6.3.1 patch
   See changes: https://github.com/symfony/framework-bundle/compare/18165b0...v6.3.1
   Release notes: https://github.com/symfony/framework-bundle/releases/tag/v6.3.1

- symfony/doctrine-bridge updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/doctrine-bridge/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/doctrine-bridge/releases/tag/v6.3.1

- symfony/http-client updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/http-client/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/http-client/releases/tag/v6.3.1

- symfony/asset-mapper downgraded from 6.3.x-dev@748ccc2 to v6.3.1 patch
   See changes: https://github.com/symfony/asset-mapper/compare/748ccc2...v6.3.1
   Release notes: https://github.com/symfony/asset-mapper/releases/tag/v6.3.1

- symfony/monolog-bridge updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/monolog-bridge/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/monolog-bridge/releases/tag/v6.3.1

- symfony/phpunit-bridge updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/phpunit-bridge/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/phpunit-bridge/releases/tag/v6.3.1

- symfony/stimulus-bundle updated from 2.x-dev@e4cd861 to 2.x-dev@257ef05 patch
   See changes: https://github.com/symfony/stimulus-bundle/compare/e4cd861...257ef05

- symfony/validator updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/validator/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/validator/releases/tag/v6.3.1

- symfony/ux-lazy-image updated from 2.x-dev@97154a5 to 2.x-dev@d1d4f0a patch
   See changes: https://github.com/symfony/ux-lazy-image/compare/97154a5...d1d4f0a

- symfony/ux-twig-component updated from 2.x-dev@912f7c6 to 2.x-dev@0c222dd patch
   See changes: https://github.com/symfony/ux-twig-component/compare/912f7c6...0c222dd

- symfony/serializer updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/serializer/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/serializer/releases/tag/v6.3.1

- symfony/ux-live-component updated from 2.x-dev@e8a7207 to 2.x-dev@73f6b7c patch
   See changes: https://github.com/symfony/ux-live-component/compare/e8a7207...73f6b7c

- symfony/ux-react updated from 2.x-dev@220460b to 2.x-dev@dc9a25c patch
   See changes: https://github.com/symfony/ux-react/compare/220460b...dc9a25c

- symfony/ux-svelte updated from 2.x-dev@c4425d2 to 2.x-dev@94d0f14 patch
   See changes: https://github.com/symfony/ux-svelte/compare/c4425d2...94d0f14

- symfony/ux-swup updated from 2.x-dev@bbd2c15 to 2.x-dev@28eed50 patch
   See changes: https://github.com/symfony/ux-swup/compare/bbd2c15...28eed50

- symfony/ux-typed updated from 2.x-dev@3971e0b to 2.x-dev@52d8a82 patch
   See changes: https://github.com/symfony/ux-typed/compare/3971e0b...52d8a82

- symfony/ux-vue updated from 2.x-dev@4d288e7 to 2.x-dev@371b35e patch
   See changes: https://github.com/symfony/ux-vue/compare/4d288e7...371b35e

- symfony/web-profiler-bundle updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/web-profiler-bundle/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/web-profiler-bundle/releases/tag/v6.3.1

- symfony/intl updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/intl/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/intl/releases/tag/v6.3.1

- symfony/dom-crawler updated from v6.3.0 to v6.3.1 patch
   See changes: https://github.com/symfony/dom-crawler/compare/v6.3.0...v6.3.1
   Release notes: https://github.com/symfony/dom-crawler/releases/tag/v6.3.1

</p>
</details>

### CODE REVIEW

**Comment by bendavies** [comment]
do not merge this. tests are failing, and they aren't run in github actions.

**Comment by bendavies** [comment]
tests fixed

**Comment by weaverryan** [comment]
> tests are failing, and they aren't run in github actions

They are now! You've been fantastic in helping with some long-term chores that I haven't been able to get to yet. THANK you.

**Comment by weaverryan** [comment]
And this is deployed 🎆

**Pull request merged**
