### PR TITLE
[LiveComponent] Add debug:live-component command

### PR DESCRIPTION
**Pull request by smnandre**
Similar to the TwigComponent one, with additional information:

* LiveProps
* LiveActions
* Pre/Post hydrate & render

### CODE REVIEW

**Comment by kbond** [comment]
A second command feels a bit confusing as `debug:twig-component` does show live components.

Wonder if we should combine into `debug:twig-component` and have a _descriptor_ system that takes care of the extra stuff live components need to show:
1. `TwigComponentDescriptor` (lives in `ux-twig-component`)
2. `LiveComponentDescriptor extends TwigComponentDescriptor` (lives in `ux-live-component`)

**Comment by WebMamba** [comment]
I agree with @kbond it look like we're going to have some duplication with the TwigComponent debug command see: https://github.com/symfony/ux/pull/1088#discussion_r1318235694 We already looked for LiveProps and LiveAction. We don't have  Pre/Post hydrate and render, and yes It can be interesting to add. But I my opinion is better to keep everything in the TrigComponent command.

**Comment by smnandre** [comment]
I'm not a big fan to bring "LiveComponent" specific code into the TwigComponent bundle to be honest... but that'll be the perfect occasion to test something i wanted to do (multiple factory)

**Comment by smnandre** [comment]
I'll split the PR in two then

* one to try the system @kbond suggested
* one to update the AsLiveComponent static methods signature that i'll need sooner

**Comment by kbond** [comment]
> I'm not a big fan to bring "LiveComponent" specific code into the TwigComponent bundle to be honest...

I think my idea would remove this. Assuming the TwigComponentDescriptor is a service, the live bundle could swap it out for the live-specific one.

**Comment by smnandre** [comment]
Closing this one (i'll use your ideas to improve the twig debug command in a near future @kbond )

**Pull request closed without merging**
