### PR TITLE
[Vue] UX Vue.js example for ux.symfony.com

### PR DESCRIPTION
**Pull request by t-richard**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | not really
| Tickets       | None
| License       | MIT

This adds the Vue.js component to ux.symfony.com

Some highlights from this PR:
* Samples are the same as the react ones, just written in Vue.js 3
* Used the Vue composition API since it's Vue 3 only and it's the new recommended syntax
* Used a composer local repository to link to the UX Vue.js component while it's not published on packagist, making this PR usable as is locally
* Changed the gradient for React to use a color closer to the "React blue"
* Used a similar gradient with the "Vue.js green"
* Fixed failing test on the Live component page

<details>
<summary>Pages screenshots</summary>

### Homepage

image

### Vue.js page

image

### Vue.js page with a search

image

### Vue.js page with an empty search

image

</details>

### CODE REVIEW

**Comment by tgalopin** [comment]
You can rebase now it's merged

**Comment by t-richard** [comment]
Rebased, I will update the PR to use the published version once it's live on packagist.

**Comment by weaverryan** [comment]
It's up on packagist now - there's not a release yet, but that's ok - we target `2.x-dev` on all the packages anyways.

**Comment by t-richard** [comment]
I saw it was on packagist but didn't realized all packages were required with 2.x-dev.

I'll update this, thanks for the heads up.

**Comment by weaverryan** [comment]
Check that out https://ux.symfony.com/vue 😎 

Thanks Thibault!

**Pull request merged**
