### PR TITLE
[LiveComponent] add empty request to help with live component tests

### LINKED ISSUE #2177: [LiveComponent] Testing forms causes exeption "There is currently no session available."
I'm trying to test my live component which contains a form. The following code raises an exception of type `Symfony\Component\HttpFoundation\Exception\SessionNotFoundException`.

My sample testcode:
```
$formComponent = $this->createLiveComponent(
        name: ProductionForm::class,
)->actingAs($testUser);

$formComponent->set('form_name.title', 'Loreum Ipsum');
```

The user and the field exist. What else is needed to get the test working?

### PR DESCRIPTION
**Pull request by daFish**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Issues        | Fix #2177 
| License       | MIT

This is an attempt to fix #2177 as now there is a session and a request.

### CODE REVIEW

**Comment by smnandre** [comment]
What i am not sure here is that tests are working in a lot of scenarios... i really would like to understand what is specific in your use case :|

**Comment by daFish** [comment]
I'm also still trying to understand the real cause. Looking at the current tests I get the impression, that they might not reflect a real world use case. But I might totally be wrong.

**Comment by smnandre** [comment]
My point is, if this is (as i kinda suppose) related to CSRF and security.. this may be fixed soon 

See: https://github.com/symfony/ux/pull/2251

**Comment by daFish** [comment]
👍🏻 I'm looking forward to #2251 being merged.

**Comment by mkrauser** [comment]
I've explained everything in https://github.com/symfony/ux/issues/2177#issuecomment-2413211416

That PR would help when testing Components with Form using the ComponentWithFormTrait

**Comment by mkrauser** [comment]
I've tested this PR some more. It seems to only fix one issue. When I try to submit the form, the CSRF-Token is invalid. 
It seems, that a new Session is created for the Submit-Request. The one generated in this PR is not used.

**Comment by daFish** [comment]
> My point is, if this is (as i kinda suppose) related to CSRF and security.. this may be fixed soon
> 
> See: #2251

After testing #2251 and disabling CSRF on my form, I can confirm this solves my issue.

**Pull request closed without merging**
