### PR TITLE
Update @hotwired/stimulus - v3.2.1

### PR DESCRIPTION
**Pull request by seb-jean**
@hotwired/stimulus 3.2.1 is released:
https://github.com/hotwired/stimulus/releases

### CODE REVIEW

**Comment by weaverryan** [comment]
Thanks for this! But there's no real advantage to doing this. In the current state, `^3.0.0` still allows projects to use 3.2.1. But by changing this, anyone using an older version (e.g. 3.2.0) will get "peer dependency" warnings, even though UX works fine on 3.2.0. So, these constraints are meant to show the *full* range of which versions we support.

Related: we do need to fix https://github.com/symfony/flex/issues/938

**Comment by stof** [comment]
Btw, due to the way the npm resolution works, bumping the min version of a peer dependency is a BC break that requires a major version (well, any kind of reducing the range actually, but it is rare to reduce it on the higher bound)

**Comment by weaverryan** [comment]
> due to the way the npm resolution works, bumping the min version of a peer dependency is a BC break that requires a major version

Can you link to why that is the case? I don't understand it, but I would love to. thx :)

**Comment by stof** [comment]
A peerDependency defines a constraint that must be satisfied by the package installed by the parent in the package tree. But it does not impact the choice of which version of the package is selected when resolving the dependencies of the parent.
That's exactly the same reason why changing the supported engine versions is a BC break in the npm ecosystem (the `engine` constraint works in a similar way than peer dependencies)

**Comment by weaverryan** [comment]
In other words, if we suddenly bumped to 3.2.1 and were actually USING some new feature in 3.2.1, the user might update and... boom! Things are broken because our code breaks due to their "too old" Stimulus. They would get a warning, but we still "broke things" on a minor update. Got it - thx Stof!

**Pull request closed without merging**
