### PR TITLE
[Twig][Live] Require Symfony 5.4+

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Tickets       | n/a
| License       | MIT

Both @weaverryan and I agree that bumping the min requirement of these library's would be beneficial. The primary reason being, the usability pre-5.3 is sub-par. Component's cannot be autoconfigured with the `AsTwigComponent`/`AsLiveComponent` attributes - they must be tagged manually. Requiring 5.4 makes documentation simpler, cleans up the test suite, and fixes some other compatibility issues. We figured, as we require PHP 8.0 already, requiring Symfony 5.4+ would be palatable.

### CODE REVIEW

**Comment by kbond** [comment]
Pinging some community members who are clearly using these library's: @Lustmored, @seb-jean, @norkunas, @allejo, @mdoutreluingne, @sabat24, @BeyerJC, @benr77. Any thoughts/objections?

**Comment by norkunas** [comment]
None from me, using 6.0+PHP8.1 for the project

**Comment by BeyerJC** [comment]
I think its a good idea. My projects are all >=5.4 , so lets go :-)

**Comment by Lustmored** [comment]
Same here - 6.0 and PHP8.1 only. In fact I was just thinking about that when making changes in test Kernel :smiley:

**Comment by sabat24** [comment]
Keeping it up to date with last active Symphony's LTS version is perfectly fine for me.

**Comment by benr77** [comment]
Agreed - 5.4 as the minimum is fine by me and I also think it's sensible to make this change sooner rather than later.

**Comment by mdoutreluingne** [comment]
It's totally understandable and acceptable to demand Symfony 5.4+, as it's an LTS release. Anyway, active projects have every interest in moving to Symfony 5.4 or more for security reasons and more... So let's go 👍

**Comment by kbond** [comment]
@symfony/mergers any objections?

**Review by nicolas-grekas — APPROVED** [review]
Works for me!

**Review by Tobion — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by allejo** [comment]
No concerns here! Using PHP8.1 & Symfony 5.4 here 🥳

**Pull request merged**
