### PR TITLE
Use simple-phpunit instead of phpunit

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Tickets       | -
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Needs at least #26 to fix deprecations.

**Review by jderusse — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Comment by lyrixx** [comment]
#26 has been merged, could you rebase this one? thanks

**Comment by nicolas-grekas** [comment]
Tests are now green.

**Review by lyrixx — APPROVED** [review]

**Comment by lyrixx** [comment]
Thanks @nicolas-grekas.

**Pull request merged**
