### PR TITLE
[CS] Update PhpCsFixer config

### PR DESCRIPTION
**Pull request by smnandre**
I took some time to check the `.php-cs-fixer.dist.php` file and 
* compared it to [symfony/symfony one](https://github.com/symfony/symfony/blob/6.4/.php-cs-fixer.dist.php) 
* checked the rules included in the rulesets (`@Symfony` `@Symfony:risky` and `@PHPUnit75Migration:risky`)

Rules already in one of the rulesets:
* [php_unit_dedicate_assert](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/php_unit/php_unit_dedicate_assert.rst) -> in @PHPUnit75Migration:risky
* [array_syntax](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/array_notation/array_syntax.rst) -> in @symfony
* [combine_nested_dirname](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/combine_nested_dirname.rst) -> in @Symfony:risky
* [native_constant_invocation](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/constant_notation/native_constant_invocation.rst) -> in @Symfony:risky (with ['strict' => false) bug do we need the difference?)

Rules unneeded:
* [protected_to_private](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/class_notation/protected_to_private.rst) -> disabled per default
* [fopen_flags](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/fopen_flags.rst) -> no fopen call in this repository code

Rules i suggest to remove:
* [list_syntax](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/list_notation/list_syntax.rst) -> not sure to see the necessity of this rule, do we need it ?
* [ordered_imports](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/import/ordered_imports.rst) -> already in @Symfony (with a different order, but the same order present in PSR and PHPCSFIXER rulesets)

--

~I also realised there is no rule to include the symfony licence header in every PHP files, should we add it ?~ (done)

---

Updated config: 

```php
 ->setRules([
        '@PHPUnit75Migration:risky' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'header_comment' => ['header' => $fileHeaderComment],
])
```

### CODE REVIEW

**Comment by weaverryan** [comment]
> I also realised there is no rule to include the symfony licence header in every PHP files, should we add it ?

Yup - that'd be great 👍

**Comment by smnandre** [comment]
Rule added / applied

**Comment by weaverryan** [comment]
> [list_syntax](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/list_notation/list_syntax.rst) -> not sure to see the necessity of this rule, do we need it ?

No idea - we can remove it and see what happens. Reading your notes, if there are other changes you want to make, go ahead and make them and we'll see how they look.

**Comment by smnandre** [comment]
I'm happy with this config :) 

I'm gonna suggest some other CI updates now 👼

**Comment by weaverryan** [comment]
Thanks Simon!

**Pull request merged**
