### PR TITLE
[Svelte] Example page for ux.symfony.com

### PR DESCRIPTION
**Pull request by ChqThomas**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| Tickets       | None
| License       | MIT

This PR adds the new Svelte component to ux.symfony.com:

- Same samples as React and Vue.js
- Only works locally with a local link to symfony/ux-svelte until the package is available on packagist

#### Svelte page (code expanded)
svelte-page

#### Homepage block
homepage-block

#### Search box
https://user-images.githubusercontent.com/7740151/232328933-2db5ac16-49f5-4012-82ee-f2843f540e22.mp4

### CODE REVIEW

**Comment by weaverryan** [comment]
This looks great ❤️. I DID just introduce some site changes i've been working on in #804 - once that's merged, we'll need a (hopefully) quick update to this PR to match the new style.

**Comment by weaverryan** [comment]
Ok #804 is merged - so this can be rebased/updated for that. Thanks!

**Comment by ChqThomas** [comment]
PR rebased and updated @weaverryan 👍
I love the new twig component syntax !!

**Comment by weaverryan** [comment]
Thank you Thomas!

**Pull request merged**
