### PR TITLE
[Autocomplete] Add support for latest tom select-version

### PR DESCRIPTION
**Pull request by daFish**
| Q             | A
| ------------- | ---
| Bug fix?      | yes (sort of)
| New feature?  | no 
| Tickets       | does not apply
| License       | MIT

This change is an attempt to enable the update of Tom Select to the recent version 2.2.2. There are 2 more or less specific issues orchidjs/tom-select/issues/500 and orchidjs/tom-select/issues/501.

### CODE REVIEW

**Comment by weaverryan** [comment]
Thanks for this! The change just affects compiling the TypeScript, correct? It doesn't affect end-users?

**Comment by daFish** [comment]
Exactly. I encountered the problem after an automated dependency update didn't work because I couldn't compile to Javascript anymore.

**Comment by weaverryan** [comment]
Ok, thanks! I see this is still a draft - is there more to add? Or are you waiting on those 2 linked issues to see if the problem might be resolved/altered there?

**Comment by daFish** [comment]
I wasn't sure if there is something else to add.

**Comment by weaverryan** [comment]
Me either! But I also didn't see what the original build failure was. But this seems reasonable.

**Comment by weaverryan** [comment]
Thanks Marcus!

**Pull request merged**
