### PR TITLE
[Twig] add a component name/template `:` "namespace" notation

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tickets       | #108
| License       | MIT

Proposes `:` as a namespace separator for component names. The default template replaces the `:` with `/` to create sub-directories. A component with the name `form:input`'s default template would be `templates/components/form/input.html.twig`.

Don't believe this would be a BC break. If someone is using the `:` notation already, they likely would have customized the template.

### CODE REVIEW

**Comment by kbond** [comment]
Adjusted this PR to just document/test using `/` as the namespace separator instead of introducing a custom notation.

**Comment by veewee** [comment]
> I've adjusted this PR to just document/test using / in the component's name as a namespace separator. After discussing with @weaverryan, we'd like avoid a custom notation for now.

That was the first thing I tried and it makes a lot of sense to use that as a separator - yet it doesn't work for live components.
Live components have their own URLs to refresh the content on the page. This URL doesn't allow the name of the live template to contain a `/`. This means that if you use / as the namespace separator, you won't be able to apply the same standard to live components. (Unless we make it possible in the router)

That is why I went with `:`.  Not saying it's the best, but the reasoning behind that separator could be:

* the old way twig did includes.
* in line with how you'dd namespace in html (xml) `<atom:button />`

**Comment by kbond** [comment]
> yet it doesn't work for live components.

Ah good point!

> in line with how you'dd namespace in html (xml) <atom:button />

Yeah, we'd like to add an html parser in the future. Slashes wouldn't work with this.

**Comment by kbond** [comment]
Ok, switched back to `:` for the reasons stated by @veewee.

**Review by weaverryan — APPROVED** [review]

**Comment by weaverryan** [comment]
Thanks Kevin!

**Pull request merged**
