### PR TITLE
[Dropzone] Enable file replacement via "drag-and-drop"

### LINKED ISSUE #1480: [UX Dropzone] drag'n'drop replacement fail
Hello,

With symfony ux dropzone, you can drag and drop files to add them to the dropzone.
Once a file is in the zone (file A), if you want to replace it with another file (file B), drag'n'drop doesn't work: file A isn't replaced in the dropzone by file B.
And file B opens in a new browser tab.

Is this a known problem? How can I solve it, please?

Thanks

uxdropzone

### PR DESCRIPTION
**Pull request by rrr63**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix #1480
| License       | MIT

Adding `dragenter` event to allow file replacement

### CODE REVIEW

**Comment by smnandre** [comment]
Hi @rrr63 ! Thank you for this PR

Could you add just a screenshot or two, for other to understand what you're adding ?

I'm wondering, you add on dragEnter, but you don't revert if the drag is canceled  ? 

Also, it would be great to add a test or two :)

**Comment by rrr63** [comment]
Hi @smnandre ,

You're right, i canceled when the drag leaves, and added a test for both, enter and leave.
Both, enter and leave are in the same test to get the right drag area from enter event.

Demo :
dropzone

**Comment by smnandre** [comment]
Wow, thank you very much! I'll try tonight but this will probably more be this week-end :)

**Comment by smnandre** [comment]
Could you add a entry in the CHANGELOG (inside the Dropzone folder) ? Next version will be 2.20

**Comment by rrr63** [comment]
Sure i can, just copied the title  :)

**Review by smnandre — APPROVED** [review]

**Comment by smnandre** [comment]
(did something weird here, but this should be / will be merged ... sorry for my mittens)

**Comment by smnandre** [comment]
Thank you @rrr63.

**Pull request merged**
