### PR TITLE
[TwigComponent] Fix EscaperExtension deprecation

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Issues        | Fix
| License       | MIT

### CODE REVIEW

**Comment by smnandre** [comment]
GOOD (last one is on LiveComponent side)

**Comment by kbond** [comment]
Thanks Simon.

**Comment by ruudk** [comment]
Thanks for fixing this! 

@kbond do you know when a new release will be provided that includes this fix?

**Comment by rhydianroberts** [comment]
Hopefully by the end of next week: https://github.com/symfony/ux/issues/1886

**Pull request merged**
