### PR TITLE
[Turbo] Add generic `<Turbo:Stream>` component

### PR DESCRIPTION
**Pull request by seb-jean**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Issues        | https://github.com/symfony/ux/pull/2298#issuecomment-2434799250
| License       | MIT

I added a generic Turbo Stream component. To use it, you can do this:

```twig
<twig:Turbo:Stream action="turbo_frame_reload" targets="#count-post" />
```

The rendering is:

```twig
<turbo-stream action="turbo_frame_reload" targets="#count-post"></turbo-stream>
```

### CODE REVIEW

**Review by Kocal — APPROVED** [review]
Can you also update the CHANGELOG here please? Thanks

**Comment by smnandre** [comment]
Is there any advantage here (apart from the syntax) ?

Because 

```html
<turbo-frame foo bar>foo bar</turbo-frame>
```

and

```twig
<twig:Turbo:Frame foo bar>
foo bar
</twig:Turbo:Frame>
```

have a real difference in term of performance.

But i get the target to cover all bases of turbo with one syntax. 

Thinking outloud here.. not sure what to do.

I wonder if we should not make a search/replace here, instead of calling an embedding component 🤷 
But then, it would be difficult to explain the differences in scope

**Comment by seb-jean** [comment]
> Can you also update the CHANGELOG here please? Thanks

Done

**Comment by seb-jean** [comment]
> Is there any advantage here (apart from the syntax) ?
> 
> Because
> 
> ```
> <turbo-frame foo bar>foo bar</turbo-frame>
> ```
> 
> and
> 
> ```
> <twig:Turbo:Frame foo bar>
> foo bar
> </twig:Turbo:Frame>
> ```
> 
> have a real difference in term of performance.
> 
> But i get the target to cover all bases of turbo with one syntax.
> 
> Thinking outloud here.. not sure what to do.
> 
> I wonder if we should not make a search/replace here, instead of calling an embedding component 🤷 But then, it would be difficult to explain the differences in scope

This comment is rather related to this PR I think no?: https://github.com/symfony/ux/pull/2303

**Review by smnandre — APPROVED** [review]

**Comment by Kocal** [comment]
Thank you @seb-jean.

**Pull request merged**
