### PR TITLE
[Site] Refactor Translator page

### PR DESCRIPTION
**Pull request by smnandre**
* remove highlight
* remove big JS controller
* add block controller
* fix some minor spacing issues
* display both locales at once

translator-bis

### CODE REVIEW

**Comment by Kocal** [comment]
Nice one :)

**Comment by smnandre** [comment]
> Nice one :)

It's only because I really, _really_ want to switch to tempest/highlight soon :))

**Comment by javiereguiluz** [comment]
Very nice! Thanks!

A minor question ... in the screenshot, why does it say `5,700% of the work is done` when passing `0.5`? It should say `50% of the work is done`, right?

**Comment by smnandre** [comment]
> Very nice! Thanks!
> 
> A minor question ... in the screenshot, why does it say `5,700% of the work is done` when passing `0.5`? It should say `50% of the work is done`, right?

I’ve not finished 😅

**Comment by smnandre** [comment]
Good for me 

translator-2

**Review by kbond — APPROVED** [review]

**Comment by kbond** [comment]
Thanks Simon.

**Pull request merged**
