### PR TITLE
[Site] updates

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Tickets       | n/a
| License       | MIT

I ran into a bit of trouble running the test suite locally so I made some changes:

- installed foundry to help with resetting/seeding the test db
- fixed deprecations
- updated deps

I also added a readme to detail the process for running the site locally.

### CODE REVIEW

**Comment by kbond** [comment]
When using the turbo stream chat demo, I get the following error when posting a message in chat:

Failed-to-send-an-update-500-Internal-Server-Error-

Must be to do with the `MERCURE_URL` variables in .env but not sure how to fix (or what to set it to locally).

**Comment by weaverryan** [comment]
About the Mercure stuff, hmm. Iirc, using Docker + the `symfony` binary should set those automatically... though I'm not seeing that locally right now. I talk very specifically in a tutorial about this, but I can't seem to see the `MERCURE_` env vars locally...

**Comment by kbond** [comment]
I should note that when I reload the page, the chat box contains my message - so appears some kind of side-effect is failing.

**Comment by weaverryan** [comment]
@kbond I think I fixed it over on #965 - looks like wrong flag, or an outdated flag (I'm sure this worked at some point - I've used this locally).

**Comment by weaverryan** [comment]
Thanks Kevin!

**Pull request merged**
