### PR TITLE
[Autocomplete] Add missing / fix translations

### PR DESCRIPTION
**Pull request by smnandre**
Used ChatGPT4+ with custom prompt

Updated messages seem more legit than the previous ones, but feel free to correct :)

### CODE REVIEW

**Comment by weaverryan** [comment]
Filling in missing translations via AI seems like a very reasonable idea. But I'm not, yet, comfortable with updating existing translations (done by humans) with the AI version.

**Comment by smnandre** [comment]
Have all the first translations (all added with the bundle at first) been done by humans ? Some seem to me they could come from Google Translate.

But i'll adapt the PR to just "add" translations first, we can discuss the existing ones after.

**Comment by smnandre** [comment]
Reverted all changes made to existing messages

**Comment by weaverryan** [comment]
Very cool - thank you Simon!

**Pull request merged**
