### PR TITLE
[LazyImage] Fix code block rendering in docs

### PR DESCRIPTION
**Pull request by mttsch**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by mttsch** [comment]
Currently renders incorrectly on website (https://symfony.com/bundles/ux-lazy-image/current/index.html#customizing-images-fetching):

Screenshot 2024-05-30 at 09 21 13

I did not check how it will render after this change!

**Comment by Kocal** [comment]
Hi, I've used `::` because the linter was not happy about it:
> Please do not use ".. code-block:: php", use "::" instead.

And so you have the same issue https://github.com/symfony/ux/actions/runs/9298650239/job/25590944633?pr=1876 

IDK how to fix it properly tho

**Comment by Kocal** [comment]
Hum, maybe removing the newline between `.. ::` and `namespace App\BlurHash;`?

**Comment by mttsch** [comment]
When checking for existing examples, I mistakenly used examples from the vendor folder. Now I searched for existing examples that are not in vendor, though I still have not checked the built result.

**Comment by kbond** [comment]
Thank you Matthias.

**Comment by Kocal** [comment]
> When checking for existing examples, I mistakenly used examples from the vendor folder. Now I searched for existing examples that are not in vendor, though I still have not checked the built result.

Looks like you were right, the code block is now properly displayed, thanks :)
image

**Pull request merged**
