### PR TITLE
[Autocomplete] Translate "Add ..." text with remote data setup

### PR DESCRIPTION
**Pull request by jonasdekeukelaere**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Issues        | Fix #... 
| License       | MIT

In https://github.com/symfony/ux/pull/2108 the "Add..." translation has been added. But this only worked for non remote data setups. This PR makes it work for remote data setup too.

Also add translation for Dutch.

### CODE REVIEW

**Review by Kocal — APPROVED** [review]
Makes sense to me, thanks :)

Could you update the Autocomplete's CHANGELOG please?

**Comment by jonasdekeukelaere** [comment]
Changelog updated

**Comment by smnandre** [comment]
Do you know why the tests are failing ?

**Comment by jonasdekeukelaere** [comment]
No idea, looks like it is the same like in https://github.com/symfony/ux/pull/2108#issuecomment-2325673608

**Review by smnandre — APPROVED** [review]

**Comment by kbond** [comment]
Thank you @jonasdekeukelaere.

**Pull request merged**
