### PR TITLE
Asset mapper integration part 2!

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tickets       | None
| License       | MIT

Hi!

Continued work to prep the UX bundles (and the new StimulusBundle) to support AssetMapper (support for WebpackEncoreBundle will not change).

Cheers!

### CODE REVIEW

**Comment by weaverryan** [comment]
Ok, all of ux.symfony.com on this branch now works with AssetMapper without Node/Webpack!

**Comment by weaverryan** [comment]
This is ready to go - it's a bit too big to review effectively, but it relates to StimulusBundle + AssetMapper, both of which will be experimental to begin with. I'll merge tomorrow.

**Comment by seb-jean** [comment]
Do you know how it could work with Tailwind?

My file

```css
/* assets\styles\app.css */

@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

I have errors:

```
GET .../assets/styles/tailwindcss/base net::ERR_ABORTED 404
GET .../assets/styles/tailwindcss/components net::ERR_ABORTED 404
GET .../assets/styles/tailwindcss/utilities net::ERR_ABORTED 404
```

**Comment by weaverryan** [comment]
That's something I'll talk about in the docs later. But the short / easiest answer immediately will be to use the Tailwind binary to build your `assets/app.css` to a `assets/build/app.css` then include THAT file - e.g. `<link href="{{ asset('build/app.css') }}">`

**Comment by seb-jean** [comment]
Thanks @weaverryan

**Comment by martin7600** [comment]
Hi,
Do you think we can use Typescript? If yes, how could we do it?

**Pull request merged**
