### PR TITLE
chore(ux.symfony.com:deps) update Twig-CS-Fixer to ^3.0

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Issues        | Fix #... 
| License       | MIT

#1948 just have been merged, and [Twig-CS-Fixer 3.0.0](https://github.com/VincentLanglet/Twig-CS-Fixer/releases/tag/3.0.0) has been released today.

Let's update it :D

PS: don't we want to use this tool on the whole project instead of only `ux.symfony.com`?

### CODE REVIEW

**Comment by smnandre** [comment]
We wanted to check first for the website, and then generalize :)

**Comment by Kocal** [comment]
> We wanted to check first for the website, and then generalize :)

Perfect, thanks :)

**Review by smnandre — APPROVED** [review]

**Comment by smnandre** [comment]
Thank .. you ;)

**Comment by kbond** [comment]
Thanks Hugo.

**Pull request merged**
