### PR TITLE
[LiveComponent] Add StimulusBundle dependency

### PR DESCRIPTION
**Pull request by stof**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/
| New feature?  | no
| Tickets       | 
| License       | MIT

As this bundle implements its feature using stimulus, it should enforce that the bundle is available.

### CODE REVIEW

**Comment by weaverryan** [comment]
Hey Stof!

There is no actual reference or usage of the Stimulus classes inside of LiveComponents. I agree that you'll need StimulusBundle in practice (because its recipe will set up the app for you), but I can't see where it's strictly required. Can you point?

Thanks!

**Comment by stof** [comment]
The whole JS logic is implemented through a Stimulus controller: https://github.com/symfony/ux/blob/2.x/src/LiveComponent/assets/src/live_controller.ts

Without stimulus, the live component will not be live. This is exactly what has been reported by someone on Slack.

**Comment by stof** [comment]
hmm, apparently, the min PHP version for StimulusBundle is higher than for other UX bundles. This does not help defining such dependencies.

**Comment by stof** [comment]
Actually, many other UX packages are relying on Stimulus for their JS logic, so it might make sense for them to have this dependency as well.

**Comment by weaverryan** [comment]
Hmm, I see. It’s weird to me to make a package like this rely on StimulusBundlewhen it doesn’t *really* need it (you could get stimulus running manually and it would work). In practice, that’s not actually doing to happen, so your PR would make life easier in practice.

**Comment by smnandre** [comment]
Done in #1946

**Pull request closed without merging**
