### PR TITLE
[Twig][Live] Drop Twig 2 support

### PR DESCRIPTION
**Pull request by smnandre**
As Symfony Twig Bridge / Twig Bundle have already dropped Twig 2 support... i think it's time for us to do the same thing :)

* TwigBundle:  https://github.com/symfony/twig-bundle/commit/bca6a836fdd2edad7c15278b2f11f3c7f204d395
* TwigBridge: https://github.com/symfony/twig-bridge/commit/34e9d77f152a8035cfafb27756930d898595b0c8

### CODE REVIEW

**Comment by smnandre** [comment]
Failure / deprecation look related to Foundry no ? cc @kbond  maybe ?

**Comment by kbond** [comment]
> Failure / deprecation look related to Foundry no ?

I'm not seeing anything with foundry in the actions log, can you link to where you're seeing this?

**Comment by smnandre** [comment]
To Browser sorry i think ? cf the deprecations 

https://github.com/symfony/ux/actions/runs/7725916788/job/21061159963#step:7:147

And _resetDatabase too ? But i'm really not sure there

**Comment by kbond** [comment]
I'm seeing this:
- https://github.com/symfony/ux/actions/runs/7725916788/job/21061159963#step:7:103 - direct deprecation caused by Twig\Node\Node::count()
- https://github.com/symfony/ux/actions/runs/7725916788/job/21061161859#step:7:100 - wrong twig exception being expected

**Comment by smnandre** [comment]
Was talking about the deprecation in the other test suite ;) 

_resetDatabase and the others are generated inside Browser i believe.

I'll look at the errors tomorrow !

**Comment by smnandre** [comment]
I'd need help there, as there is nothing counting Twig Nodes in the test code, and i'm not the most qualified i guess to fix this part of the tests.

@kbond @weaverryan @WebMamba ?

**Comment by weaverryan** [comment]
Sure! What do you mean by counting twig nodes?

**Comment by smnandre** [comment]
LiveComponent 8.1 fails because of direct deprecation

see: https://github.com/symfony/ux/actions/runs/7770236144/job/21190171213?pr=1436 

```
OK (220 tests, 708 assertions)

Remaining direct deprecation notices (1)

  1x: Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, 
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

    1x in BatchActionControllerTest::testCanBatchActions from Symfony\UX\LiveComponent\Tests\Functional\Controller
```

--> [Symfony\UX\LiveComponent\Tests\Functional\Controller\BatchActionControllerTest](https://github.com/symfony/ux/blob/2.x/src/LiveComponent/tests/Functional/Controller/BatchActionControllerTest.php)

**Comment by weaverryan** [comment]
Thanks Simon! We'll solidify the tests and deprecations outside of this PR, as there are several moving parts

**Pull request merged**
